blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/evren/appband/discussions
    about: For open-ended questions and ideas, please open a discussion.
